config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
  }

  resources :vehicles
  resources :campers

  namespace :admin do
    resources :users
    resources :vehicles do
      collection do 
        get :import
        post :process_import
      end
    end
    resources :campers do
      collection do 
        get :import
        post :process_import
      end
    end
  end
end

app/models/vehicle.rb
# == Schema Information
#
# Table name: vehicles
#
#  id                        :integer          not null, primary key
#  vehicle_make              :string
#  vehicle_model_title       :string
#  vehicle_model_descritpion :string
#  start_year                :string
#  end_year                  :string
#  with_breaks               :string
#  ball_mass_max             :string
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  name                      :string
#

class Vehicle < ApplicationRecord
  after_validation :set_name

  private
  def set_name
    if vehicle_make_changed? || vehicle_model_title_changed?
      self.name = [vehicle_make.to_s.strip, vehicle_model_title.to_s.strip].join(" ")
    end
  end
end

app/controllers/admin/vehicles_controller.rb
module Admin
  class VehiclesController < BaseController
    before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

    # GET /vehicles
    # GET /vehicles.json
    def index
      @vehicles = Vehicle.all
    end

    # GET /vehicles/1
    # GET /vehicles/1.json
    def show
    end

    # GET /vehicles/new
    def new
      @vehicle = Vehicle.new
    end

    # GET /vehicles/1/edit
    def edit
    end

    def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to admin_vehicles_url, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to admin_vehicles_url, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to admin_vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import

  end

  def process_import
    csv = CSV.parse(File.read(params[:file].path), :headers => false)
    csv.each do |row|
      next if row[0] == 'VEHICLE MAKE' || row[0].blank?
      Vehicle.create vehicle_make: row[0],
                     vehicle_model_title: row[1],
                     vehicle_model_descritpion: row[2],
                     start_year: row[3],
                     end_year: row[4],
                     with_breaks: row[6],
                     ball_mass_max: row[7]
    end

    redirect_to admin_vehicles_url, 
                notice: 'Vehicles was successfully imported.'
  end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_vehicle
        @vehicle = Vehicle.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def vehicle_params
        params.require(:vehicle).permit(:vehicle_make, :vehicle_model_title, :vehicle_model_descritpion, :start_year, :end_year, :with_breaks, :ball_mass_max)
      end
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  layout "visitors"
  def index
    @vehicles = Vehicle.ransack(params[:q])
                       .result

    render 'index', layout: false
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/admin/vehicles/_form.html.erb
<%= simple_form_for([:admin, @vehicle]) do |f| %>

  <div class="form-inputs">
    <%= f.input :vehicle_make %>
    <%= f.input :vehicle_model_title %>
    <%= f.input :vehicle_model_descritpion %>
    <%= f.input :start_year %>
    <%= f.input :end_year %>
    <%= f.input :with_breaks %>
    <%= f.input :ball_mass_max %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

app/views/admin/vehicles/import.html.erb
<h1>Import Vehicles</h1>

<%= simple_form_for :import, url: process_import_admin_vehicles_path, html: { multipart: true} do |f| %>
  <div class="form-group">
    <label>File:</label>
    <input type="file" name="file" class="form-control">
  </div>
  <button class="btn btn-outline-success">
    Import
  </button>
<% end %>

app/views/admin/vehicles/index.html.erb
<div class="row">
  <div class="col-md-6 col-sm-6 col-6">
    <h1>Vehicles</h1>
  </div>
  <div class="col-md-6 col-sm-6 col-6 text-right">
    <a class="btn btn-outline-primary" href="<%= import_admin_vehicles_path %>">Import</a>
    <a class="btn btn-outline-primary" href="<%= new_admin_vehicle_path %>">New</a>
  </div>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Vehicle make</th>
      <th>Vehicle model title</th>
      <th>Vehicle model descritpion</th>
      <th>Start year</th>
      <th>End year</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.vehicle_make %></td>
        <td><%= vehicle.vehicle_model_title %></td>
        <td><%= vehicle.vehicle_model_descritpion %></td>
        <td><%= vehicle.start_year %></td>
        <td><%= vehicle.end_year %></td>
        <td><%= link_to 'Show', admin_vehicle_path(vehicle) %> |
        <%= link_to 'Edit', edit_admin_vehicle_path(vehicle) %> |
        <%= link_to 'Destroy', admin_vehicle_path(vehicle), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

app/views/admin/vehicles/show.html.erb
<div class="row">
  <div class="col-md-6 col-sm-6 col-6">
    <h1>Vehicle</h1>
  </div>
  <div class="col-md-6 col-sm-6 col-6 text-right">
      <a class="btn btn-outline-primary" href="<%= edit_admin_vehicle_path(@vehicle) %>">Edit</a>
  </div>
</div>
<hr>
<p>
  <strong>Vehicle make:</strong>
  <%= @vehicle.vehicle_make %>
</p>

<p>
  <strong>Vehicle model title:</strong>
  <%= @vehicle.vehicle_model_title %>
</p>

<p>
  <strong>Vehicle model descritpion:</strong>
  <%= @vehicle.vehicle_model_descritpion %>
</p>

<p>
  <strong>Start year:</strong>
  <%= @vehicle.start_year %>
</p>

<p>
  <strong>End year:</strong>
  <%= @vehicle.end_year %>
</p>


<p>
  <strong>With breaks:</strong>
  <%= @vehicle.with_breaks %>
</p>

<p>
  <strong>Ball mass:</strong>
  <%= @vehicle.ball_mass_max %>
</p>