config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
  }

  resources :vehicles
  resources :campers

  namespace :admin do
    resources :users
    resources :vehicles do
      collection do 
        get :import
        post :process_import
      end
    end
    resources :campers do
      collection do 
        get :import
        post :process_import
      end
    end
  end
end

app/models/camper.rb
# == Schema Information
#
# Table name: campers
#
#  id                     :integer          not null, primary key
#  brand                  :string
#  model                  :string
#  version                :string
#  display_price          :float
#  price_min              :float
#  price_max              :float
#  capacity               :float
#  link                   :string
#  gvm                    :string
#  ball_weight            :float
#  solar                  :boolean
#  roof_rack              :boolean
#  alloy_wheels           :boolean
#  all_terrain_tyres      :boolean
#  mud_tyres              :boolean
#  twin_spares            :boolean
#  large_water            :boolean
#  deep_cycle_batteries   :boolean
#  diesel_heating         :boolean
#  air_conditioning       :boolean
#  tv                     :boolean
#  ensuite                :boolean
#  hot_water              :boolean
#  independent_suspension :boolean
#  priority               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  type_a                 :string
#  type_b                 :string
#  type_c                 :string
#  atm                    :string
#  tare                   :decimal(, )
#

class Camper < ApplicationRecord
  INCLUSIONS = [
    "Solar Panel",
    "Roof racks",
    "Alloy wheels",
    "All terrain types",
    "Mud tires",
    "Twin spare",
    "100L+ Water Storage",
    "Deep Cycle Batteries",
    "Diesel Heating",
    "Air Conditioning",
    "Television Screen",
    "Ensuite Facilities",
    "Hot Water System",
    "Independent Suspension"
  ]
end

app/controllers/admin/campers_controller.rb
module Admin
  class CampersController < BaseController
    before_action :set_camper, only: [:show, :edit, :update, :destroy]

    # GET /campers
    # GET /campers.json
    def index
      @campers = Camper.all
    end

    # GET /campers/1
    # GET /campers/1.json
    def show
    end

    # GET /campers/new
    def new
      @camper = Camper.new
    end

    # GET /campers/1/edit
    def edit
    end

    # POST /campers
    # POST /campers.json
    def create
    @camper = Camper.new(camper_params)

    respond_to do |format|
      if @camper.save
        format.html { redirect_to admin_campers_url, notice: 'Camper was successfully created.' }
        format.json { render :show, status: :created, location: @camper }
      else
        format.html { render :new }
        format.json { render json: @camper.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @camper.update(camper_params)
        format.html { redirect_to admin_campers_url, notice: 'Camper was successfully updated.' }
        format.json { render :show, status: :ok, location: @camper }
      else
        format.html { render :edit }
        format.json { render json: @camper.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @camper.destroy
    respond_to do |format|
      format.html { redirect_to admin_campers_url, notice: 'Camper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import

  end

  def process_import
    csv = CSV.parse(File.read(params[:file].path), :headers => false)
    csv.each do |row|
      next if row[0].blank?
      Camper.create brand: row[0],
                     model: row[1],
                     version: row[2],
                     display_price: row[3],
                     capacity: row[4],
                     link: row[5],
                     type_a: row[6],
                     type_b: row[7],
                     type_c: row[8],
                     atm: row[9],
                     tare: row[10],
                     ball_weight: row[11],
                     solar: row[12] == "YES" ? true : false,
                     roof_rack: row[13] == "YES" ? true : false,
                     alloy_wheels: row[14] == "YES" ? true : false,
                     all_terrain_tyres: row[15] == "YES" ? true : false,
                     mud_tyres: row[16] == "YES" ? true : false,
                     twin_spares: row[17] == "YES" ? true : false,
                     large_water: row[18] == "YES" ? true : false,
                     deep_cycle_batteries: row[19] == "YES" ? true : false,
                     diesel_heating: row[20] == "YES" ? true : false,
                     air_conditioning: row[21] == "YES" ? true : false,
                     tv: row[22] == "YES" ? true : false,
                     ensuite: row[23] == "YES" ? true : false,
                     hot_water: row[24] == "YES" ? true : false,
                     independent_suspension: row[25] == "YES" ? true : false,
                     priority: row[26]
    end

    redirect_to admin_campers_url, 
                notice: 'Campers was successfully imported.'
  end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_camper
        @camper = Camper.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def camper_params
        params.require(:camper).permit(:brand, :model, :version, :display_price, :price_min, :price_max, :capacity, :link, :type_a, :type_b, :type_c, :atm, :tare, :gvm, :ball_weight, :solar, :roof_rack, :alloy_wheels, :all_terrain_tyres, :mud_tyres, :twin_spares, :large_water, :deep_cycle_batteries, :diesel_heating, :air_conditioning, :tv, :ensuite, :hot_water, :independent_suspension, :priority)
      end
  end
end

app/controllers/campers_controller.rb
class CampersController < ApplicationController
  def index
    @search = Camper

    match_fields = {
      "Solar Panel" => 'solar',
      "Roof racks" => 'roof_rack',
      "Alloy wheels" => 'alloy_wheels',
      "All terrain types" => 'all_terrain_tyres',
      "Mud tires" => 'mud_tyres',
      "Twin spare" => 'twin_spares',
      "100L+ Water Storage" => 'large_water',
      "Deep Cycle Batteries" => 'deep_cycle_batteries',
      "Diesel Heating" => 'diesel_heating',
      "Air Conditioning" => 'air_conditioning',
      "Television Screen" => 'tv',
      "Ensuite Facilities" => 'ensuite',
      "Hot Water System" => 'hot_water',
      "Independent Suspension"  => 'independent_suspension'
    }

    if params[:inclusions].present?
      params[:inclusions].each do |field|
        @search = @search.where("#{match_fields[field]}  = ?", true)
      end
    end

    @search = @search.ransack(params[:q])

    @campers = @search.result
  end

  def show
    @camper = Camper.find(params[:id])
  end
end

app/helpers/campers_helper.rb
module CampersHelper
end

app/views/admin/campers/_form.html.erb
<%= simple_form_for([:admin, @camper]) do |f| %>

  <div class="form-inputs">
    <%= f.input :brand %>
    <%= f.input :model %>
    <%= f.input :version %>
    <%= f.input :display_price %>
    <%= f.input :capacity %>
    <%= f.input :link %>

    <%= f.input :type_a %>
    <%= f.input :type_b %>
    <%= f.input :type_c %>
    <%= f.input :atm %>
    <%= f.input :tare %>
    <%= f.input :priority %>
    
    <%= f.input :ball_weight %>
    <%= f.input :solar %>
    <%= f.input :roof_rack %>
    <%= f.input :alloy_wheels %>
    <%= f.input :all_terrain_tyres %>
    <%= f.input :mud_tyres %>
    <%= f.input :twin_spares %>
    <%= f.input :large_water %>
    <%= f.input :deep_cycle_batteries %>
    <%= f.input :diesel_heating %>
    <%= f.input :air_conditioning %>
    <%= f.input :tv %>
    <%= f.input :ensuite %>
    <%= f.input :hot_water %>
    <%= f.input :independent_suspension %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/campers/edit.html.erb
<h1>Editing Camper</h1>

<%= render 'form', camper: @camper %>

app/views/admin/campers/import.html.erb
<h1>Import Campers</h1>

<%= simple_form_for :import, url: process_import_admin_campers_path, html: { multipart: true} do |f| %>
  <div class="form-group">
    <label>File:</label>
    <input type="file" name="file" class="form-control">
  </div>
  <button class="btn btn-outline-success">
    Import
  </button>
<% end %>

app/views/admin/campers/index.html.erb
<div class="row">
  <div class="col-md-6 col-sm-6 col-6">
    <h1>Campers</h1>
  </div>
  <div class="col-md-6 col-sm-6 col-6 text-right">
    <a class="btn btn-outline-primary" href="<%= import_admin_campers_path %>">Import</a>
    <a class="btn btn-outline-primary" href="<%= new_admin_camper_path %>">New</a>
  </div>
</div>


<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Version</th>
      <th>Display price</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @campers.each do |camper| %>
      <tr>
        <td><%= camper.brand %></td>
        <td><%= camper.model %></td>
        <td><%= camper.version %></td>
        <td><%= camper.display_price %></td>
        <td><%= link_to 'Show', admin_camper_path(camper) %> |
        <%= link_to 'Edit', edit_admin_camper_path(camper) %> |
        <%= link_to 'Destroy', admin_camper_path(camper), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/campers/new.html.erb
<h1>New Camper</h1>

<%= render 'form', camper: @camper %>

app/views/admin/campers/show.html.erb
<div class="row">
  <div class="col-md-6 col-sm-6 col-6">
    <h1>Campers</h1>
  </div>
  <div class="col-md-6 col-sm-6 col-6 text-right">
      <a class="btn btn-outline-primary" href="<%= edit_admin_camper_path(@camper) %>">Edit</a>
  </div>
</div>
<hr>

<p>
  <strong>Brand:</strong>
  <%= @camper.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @camper.model %>
</p>

<p>
  <strong>Version:</strong>
  <%= @camper.version %>
</p>

<p>
  <strong>Display price:</strong>
  <%= @camper.display_price %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @camper.capacity %>
</p>

<p>
  <strong>Link:</strong>
  <%= @camper.link %>
</p>

<p>
  <strong>Type A:</strong>
  <%= @camper.type_a %>
</p>

<p>
  <strong>Type B:</strong>
  <%= @camper.type_b %>
</p>

<p>
  <strong>Type C:</strong>
  <%= @camper.type_c %>
</p>

<p>
  <strong>ATM:</strong>
  <%= @camper.atm %>
</p>

<p>
  <strong>TARE:</strong>
  <%= @camper.tare %>
</p>

<p>
  <strong>Ball weight:</strong>
  <%= @camper.ball_weight %>
</p>

<p>
  <strong>Solar:</strong>
  <%= @camper.solar %>
</p>

<p>
  <strong>Roof rack:</strong>
  <%= @camper.roof_rack %>
</p>

<p>
  <strong>Alloy wheels:</strong>
  <%= @camper.alloy_wheels %>
</p>

<p>
  <strong>All terrain tyres:</strong>
  <%= @camper.all_terrain_tyres %>
</p>

<p>
  <strong>Mud tyres:</strong>
  <%= @camper.mud_tyres %>
</p>

<p>
  <strong>Twin spares:</strong>
  <%= @camper.twin_spares %>
</p>

<p>
  <strong>1000l water:</strong>
  <%= @camper.large_water %>
</p>

<p>
  <strong>Deep cycle batteries:</strong>
  <%= @camper.deep_cycle_batteries %>
</p>

<p>
  <strong>Diesel heating:</strong>
  <%= @camper.diesel_heating %>
</p>

<p>
  <strong>Air conditioning:</strong>
  <%= @camper.air_conditioning %>
</p>

<p>
  <strong>Tv:</strong>
  <%= @camper.tv %>
</p>

<p>
  <strong>Ensuite:</strong>
  <%= @camper.ensuite %>
</p>

<p>
  <strong>Hot water:</strong>
  <%= @camper.hot_water %>
</p>

<p>
  <strong>Independent suspension:</strong>
  <%= @camper.independent_suspension %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @camper.priority %>
</p>