config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
  }

  resources :vehicles
  resources :campers

  namespace :admin do
    resources :users
    resources :vehicles do
      collection do 
        get :import
        post :process_import
      end
    end
    resources :campers do
      collection do 
        get :import
        post :process_import
      end
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  first_name             :string
#  last_name              :string
#  role                   :string
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_type        :string
#  invited_by_id          :integer
#  invitations_count      :integer          default(0)
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ROLES = [
    ROLE_ADMIN = "Admin",
    ROLE_REGULAR = "Regular"
]

devise :invitable, :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable


validates :first_name, presence: true, length: { maximum: 50 }
validates :last_name, presence: true, length: { maximum: 50 }
validates :role, inclusion: ROLES, presence: true

before_validation :set_role

def full_name
  [first_name, last_name].join(" ")
end

def admin?
  self.role == ROLE_ADMIN
end

private
def set_role
  self.role = ROLE_REGULAR if self.role.blank?
end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < BaseController
    before_action :set_user, only: [:edit, :update, :destroy]

    def index
      @users = User.order(last_name: :asc).page(params[:page])
    end

    def new
      @user = User.new role: User::ROLE_REGULAR
    end

    def create
      @user = User.new user_params
      if @user.save
        redirect_to admin_users_path, notice: "User has beed created successfully"
      else
        render :new
      end
    end

    def edit
    end

    def destroy
      @user.delete
      redirect_to admin_users_path, notice: "User has beed deleted successfully"
    end

    def update
      if @user.update user_params
        redirect_to admin_users_path, notice: "User has beed updated successfully"
      else
        render :edit
      end
    end

    private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :run,
                                   :password, :password_confirmation, :role)
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def sign_up_params
params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, @user] do |f| %>

  <%= f.input :first_name, required: true %>
  <%= f.input :last_name, required: true %>
  <%= f.input :email, required: true, autofocus: true %>
  <%= f.input :role, required: true, collection: User::ROLES %>
  <% if @user.new_record? %>
  <%= f.input :password, required: true %>
  <%= f.input :password_confirmation, required: true %>
  <% end %>
  <%= f.button :submit, class: "btn btn btn-success" %>

<% end %>

app/views/admin/users/edit.html.erb
<% content_for :breadcrumb do %>
<ul class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="<%= admin_users_path %>">Users</a></li>
  <li class="breadcrumb-item active">Edit</li>
</ul>
<% end %>


<div class="row">
  <div class="col-sm-6">
    <h4>User information</h4>
    <%= render 'form' %>
  </div>
  <div class="col-sm-6">
    <h4>Change password</h4>
    <%= simple_form_for [:admin, @user] do |f| %>
      <%= f.input :password, required: true %>
      <%= f.input :password_confirmation, required: true %>
      <%= f.button :submit, class: "btn btn btn-success", value: "Change password" %>
    <% end %>
</div>

app/views/admin/users/index.html.erb
<% content_for :breadcrumb do %>
<ul class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="<%= admin_users_path %>">Users</a></li>
  <li class="breadcrumb-item active">Index</li>
</ul>
<% end %>

<div class="row">
  <div class="col-md-6">
    <h1>User</h1>
  </div>
  <div class="col-md-6 text-right">
    <a class="btn btn-outline-primary" href="<%= new_admin_user_path %>">New User</a>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Full name</th>
      <th>Email</th>
      <th>Permission</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.full_name %></td>
      <td><%= user.email %></td>
      <td><%= user.role %></td>
      <td>
        <a href="<%= edit_admin_user_path(user) %>" class="btn btn-outline-info">
          Edit
        </a>
        <a href="<%= admin_user_path(user) %>" data-method="DELETE" class="btn btn-outline-danger"
           data-confirm="Are you sure?">
          Delete
        </a>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
  <div class="col-sm-6">
    <%= page_entries_info @users %>
  </div>
  <div class="col-sm-6">
    <%= paginate @users %>
  </div>
</div>

app/views/admin/users/new.html.erb
<% content_for :breadcrumb do %>
<ul class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="<%= admin_users_path %>">Users</a></li>
  <li class="breadcrumb-item active">New</li>
</ul>
<% end %>

<h1>New user</h1>

<div class="row">
  <div class="col-sm-6">
    <%= render 'form' %>
  </div>
</div>