config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
  }

  resources :vehicles
  resources :campers

  namespace :admin do
    resources :users
    resources :vehicles do
      collection do 
        get :import
        post :process_import
      end
    end
    resources :campers do
      collection do 
        get :import
        post :process_import
      end
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/">CamperApp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in? %>
      <ul class="navbar-nav mr-auto">


        <% if can?(:manage, User)%>
            <li class="nav-item">
            <a class="nav-link" href="<%= admin_vehicles_path %>">Vehicles</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= admin_campers_path %>">Campers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= admin_users_path %>">Users</a>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link" href="<%= admin_vehicles_path %>">Vehicles</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= admin_campers_path %>">Campers</a>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
<li class="nav-item">
  <a class="nav-link"><%= current_user.full_name %></a>
</li>
<li class="nav-item">
  <a data-method="DELETE" class="btn-outline-danger btn" href="<%= destroy_user_session_path %>">Log out</a>
</li>
</ul>
<% else %>
<ul class="navbar-nav ml-auto">
  <li>
    <a class="btn-outline-primary btn" href="<%= new_user_session_path %>">Log in</a>
  </li>
</ul>
<% end %>
</div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Camper App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Template" %>">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <main role="main">
      <%= yield %>
    </main>
    <%= yield(:page_js) %>
  </body>
</html>

app/views/layouts/visitors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Camper App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Template" %>">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
      <%= yield %>
    <%= yield(:page_js) %>
  </body>
</html>